export enum Endpoint {
  UserGetAll = "/api/user/all",
  UserCurrent = "/api/user/current",
  UserRegister = "/api/user/register",
  UserLogin = "/api/user/login",
  UserLogout = "/api/user/logout",
  UserEdit = "/api/user/{id}/edit",
  UserGet = "/api/user/{id}",
  BookGetAll = "/api/book/all",
  BookAdd = "/api/book/add",
  BookEdit = "/api/book/{id}/edit",
  BookGet = "/api/book/{id}",
  ShelfGetAll = "/api/shelf/all",
  ShelfAddBook = "/api/shelf/add-book",
  ShelfRemoveBook = "/api/shelf/remove-book",
  ShelfAdd = "/api/shelf/add",
  ShelfEdit = "/api/shelf/{id}/edit",
  ShelfGet = "/api/shelf/{id}",
  AuthorAdd = "/api/author/add",
  AuthorEdit = "/api/author/{id}/edit",
  AuthorGetAll = "/api/author/all",
  AuthorGetBooks = "/api/author/{id}/books",
  AuthorGet = "/api/author/{id}",
}
